export const CURRENCIES = [
{"symbol" : "AED", "name" : "AED - United Arab Emirates Dirham"},
{"symbol" : "AFN", "name" : "AFN - Afghanistan Afghani"},
{"symbol" : "ALL", "name" : "ALL - Albania Lek"},
{"symbol" : "AMD", "name" : "AMD - Armenia Dram"},
{"symbol" : "ANG", "name" : "ANG - Netherlands Antilles Guilder"},
{"symbol" : "AOA", "name" : "AOA - Angola Kwanza"},
{"symbol" : "ARS", "name" : "ARS - Argentina Peso"},
{"symbol" : "AUD", "name" : "AUD - Australia Dollar"},
{"symbol" : "AWG", "name" : "AWG - Aruba Guilder"},
{"symbol" : "AZN", "name" : "AZN - Azerbaijan New Manat"},
{"symbol" : "BAM", "name" : "BAM - Bosnia and Herzegovina Convertible Marka"},
{"symbol" : "BBD", "name" : "BBD - Barbados Dollar"},
{"symbol" : "BDT", "name" : "BDT - Bangladesh Taka"},
{"symbol" : "BGN", "name" : "BGN - Bulgaria Lev"},
{"symbol" : "BHD", "name" : "BHD - Bahrain Dinar"},
{"symbol" : "BIF", "name" : "BIF - Burundi Franc"},
{"symbol" : "BMD", "name" : "BMD - Bermuda Dollar"},
{"symbol" : "BND", "name" : "BND - Brunei Darussalam Dollar"},
{"symbol" : "BOB", "name" : "BOB - Bolivia Boliviano"},
{"symbol" : "BRL", "name" : "BRL - Brazil Real"},
{"symbol" : "BSD", "name" : "BSD - Bahamas Dollar"},
{"symbol" : "BTN", "name" : "BTN - Bhutan Ngultrum"},
{"symbol" : "BWP", "name" : "BWP - Botswana Pula"},
{"symbol" : "BYR", "name" : "BYR - Belarus Ruble"},
{"symbol" : "BZD", "name" : "BZD - Belize Dollar"},
{"symbol" : "CAD", "name" : "CAD - Canada Dollar"},
{"symbol" : "CDF", "name" : "CDF - Congo/Kinshasa Franc"},
{"symbol" : "CHF", "name" : "CHF - Switzerland Franc"},
{"symbol" : "CLP", "name" : "CLP - Chile Peso"},
{"symbol" : "CNY", "name" : "CNY - China Yuan Renminbi"},
{"symbol" : "COP", "name" : "COP - Colombia Peso"},
{"symbol" : "CRC", "name" : "CRC - Costa Rica Colon"},
{"symbol" : "CUC", "name" : "CUC - Cuba Convertible Peso"},
{"symbol" : "CUP", "name" : "CUP - Cuba Peso"},
{"symbol" : "CVE", "name" : "CVE - Cape Verde Escudo"},
{"symbol" : "CZK", "name" : "CZK - Czech Republic Koruna"},
{"symbol" : "DJF", "name" : "DJF - Djibouti Franc"},
{"symbol" : "DKK", "name" : "DKK - Denmark Krone"},
{"symbol" : "DOP", "name" : "DOP - Dominican Republic Peso"},
{"symbol" : "DZD", "name" : "DZD - Algeria Dinar"},
{"symbol" : "EGP", "name" : "EGP - Egypt Pound"},
{"symbol" : "ERN", "name" : "ERN - Eritrea Nakfa"},
{"symbol" : "ETB", "name" : "ETB - Ethiopia Birr"},
{"symbol" : "EUR", "name" : "EUR - Euro Member Countries"},
{"symbol" : "FJD", "name" : "FJD - Fiji Dollar"},
{"symbol" : "FKP", "name" : "FKP - Falkland Islands (Malvinas) Pound"},
{"symbol" : "GBP", "name" : "GBP - United Kingdom Pound"},
{"symbol" : "GEL", "name" : "GEL - Georgia Lari"},
{"symbol" : "GGP", "name" : "GGP - Guernsey Pound"},
{"symbol" : "GHS", "name" : "GHS - Ghana Cedi"},
{"symbol" : "GIP", "name" : "GIP - Gibraltar Pound"},
{"symbol" : "GMD", "name" : "GMD - Gambia Dalasi"},
{"symbol" : "GNF", "name" : "GNF - Guinea Franc"},
{"symbol" : "GTQ", "name" : "GTQ - Guatemala Quetzal"},
{"symbol" : "GYD", "name" : "GYD - Guyana Dollar"},
{"symbol" : "HKD", "name" : "HKD - Hong Kong Dollar"},
{"symbol" : "HNL", "name" : "HNL - Honduras Lempira"},
{"symbol" : "HRK", "name" : "HRK - Croatia Kuna"},
{"symbol" : "HTG", "name" : "HTG - Haiti Gourde"},
{"symbol" : "HUF", "name" : "HUF - Hungary Forint"},
{"symbol" : "IDR", "name" : "IDR - Indonesia Rupiah"},
{"symbol" : "ILS", "name" : "ILS - Israel Shekel"},
{"symbol" : "IMP", "name" : "IMP - Isle of Man Pound"},
{"symbol" : "INR", "name" : "INR - India Rupee"},
{"symbol" : "IQD", "name" : "IQD - Iraq Dinar"},
{"symbol" : "IRR", "name" : "IRR - Iran Rial"},
{"symbol" : "ISK", "name" : "ISK - Iceland Krona"},
{"symbol" : "JEP", "name" : "JEP - Jersey Pound"},
{"symbol" : "JMD", "name" : "JMD - Jamaica Dollar"},
{"symbol" : "JOD", "name" : "JOD - Jordan Dinar"},
{"symbol" : "JPY", "name" : "JPY - Japan Yen"},
{"symbol" : "KES", "name" : "KES - Kenya Shilling"},
{"symbol" : "KGS", "name" : "KGS - Kyrgyzstan Som"},
{"symbol" : "KHR", "name" : "KHR - Cambodia Riel"},
{"symbol" : "KMF", "name" : "KMF - Comoros Franc"},
{"symbol" : "KPW", "name" : "KPW - Korea (North) Won"},
{"symbol" : "KRW", "name" : "KRW - Korea (South) Won"},
{"symbol" : "KWD", "name" : "KWD - Kuwait Dinar"},
{"symbol" : "KYD", "name" : "KYD - Cayman Islands Dollar"},
{"symbol" : "KZT", "name" : "KZT - Kazakhstan Tenge"},
{"symbol" : "LAK", "name" : "LAK - Laos Kip"},
{"symbol" : "LBP", "name" : "LBP - Lebanon Pound"},
{"symbol" : "LKR", "name" : "LKR - Sri Lanka Rupee"},
{"symbol" : "LRD", "name" : "LRD - Liberia Dollar"},
{"symbol" : "LSL", "name" : "LSL - Lesotho Loti"},
{"symbol" : "LTL", "name" : "LTL - Lithuania Litas"},
{"symbol" : "LVL", "name" : "LVL - Latvia Lat"},
{"symbol" : "LYD", "name" : "LYD - Libya Dinar"},
{"symbol" : "MAD", "name" : "MAD - Morocco Dirham"},
{"symbol" : "MDL", "name" : "MDL - Moldova Leu"},
{"symbol" : "MGA", "name" : "MGA - Madagascar Ariary"},
{"symbol" : "MKD", "name" : "MKD - Macedonia Denar"},
{"symbol" : "MMK", "name" : "MMK - Myanmar (Burma) Kyat"},
{"symbol" : "MNT", "name" : "MNT - Mongolia Tughrik"},
{"symbol" : "MOP", "name" : "MOP - Macau Pataca"},
{"symbol" : "MRO", "name" : "MRO - Mauritania Ouguiya"},
{"symbol" : "MUR", "name" : "MUR - Mauritius Rupee"},
{"symbol" : "MVR", "name" : "MVR - Maldives (Maldive Islands) Rufiyaa"},
{"symbol" : "MWK", "name" : "MWK - Malawi Kwacha"},
{"symbol" : "MXN", "name" : "MXN - Mexico Peso"},
{"symbol" : "MYR", "name" : "MYR - Malaysia Ringgit"},
{"symbol" : "MZN", "name" : "MZN - Mozambique Metical"},
{"symbol" : "NAD", "name" : "NAD - Namibia Dollar"},
{"symbol" : "NGN", "name" : "NGN - Nigeria Naira"},
{"symbol" : "NIO", "name" : "NIO - Nicaragua Cordoba"},
{"symbol" : "NOK", "name" : "NOK - Norway Krone"},
{"symbol" : "NPR", "name" : "NPR - Nepal Rupee"},
{"symbol" : "NZD", "name" : "NZD - New Zealand Dollar"},
{"symbol" : "OMR", "name" : "OMR - Oman Rial"},
{"symbol" : "PAB", "name" : "PAB - Panama Balboa"},
{"symbol" : "PEN", "name" : "PEN - Peru Nuevo Sol"},
{"symbol" : "PGK", "name" : "PGK - Papua New Guinea Kina"},
{"symbol" : "PHP", "name" : "PHP - Philippines Peso"},
{"symbol" : "PKR", "name" : "PKR - Pakistan Rupee"},
{"symbol" : "PLN", "name" : "PLN - Poland Zloty"},
{"symbol" : "PYG", "name" : "PYG - Paraguay Guarani"},
{"symbol" : "QAR", "name" : "QAR - Qatar Riyal"},
{"symbol" : "RON", "name" : "RON - Romania New Leu"},
{"symbol" : "RSD", "name" : "RSD - Serbia Dinar"},
{"symbol" : "RUB", "name" : "RUB - Russia Ruble"},
{"symbol" : "RWF", "name" : "RWF - Rwanda Franc"},
{"symbol" : "SAR", "name" : "SAR - Saudi Arabia Riyal"},
{"symbol" : "SBD", "name" : "SBD - Solomon Islands Dollar"},
{"symbol" : "SCR", "name" : "SCR - Seychelles Rupee"},
{"symbol" : "SDG", "name" : "SDG - Sudan Pound"},
{"symbol" : "SEK", "name" : "SEK - Sweden Krona"},
{"symbol" : "SGD", "name" : "SGD - Singapore Dollar"},
{"symbol" : "SHP", "name" : "SHP - Saint Helena Pound"},
{"symbol" : "SLL", "name" : "SLL - Sierra Leone Leone"},
{"symbol" : "SOS", "name" : "SOS - Somalia Shilling"},
{"symbol" : "SPL", "name" : "SPL - Seborga Luigino"},
{"symbol" : "SRD", "name" : "SRD - Suriname Dollar"},
{"symbol" : "STD", "name" : "STD - São Tomé and Príncipe Dobra"},
{"symbol" : "SVC", "name" : "SVC - El Salvador Colon"},
{"symbol" : "SYP", "name" : "SYP - Syria Pound"},
{"symbol" : "SZL", "name" : "SZL - Swaziland Lilangeni"},
{"symbol" : "THB", "name" : "THB - Thailand Baht"},
{"symbol" : "TJS", "name" : "TJS - Tajikistan Somoni"},
{"symbol" : "TMT", "name" : "TMT - Turkmenistan Manat"},
{"symbol" : "TND", "name" : "TND - Tunisia Dinar"},
{"symbol" : "TOP", "name" : "TOP - Tonga Pa'anga"},
{"symbol" : "TRY", "name" : "TRY - Turkey Lira"},
{"symbol" : "TTD", "name" : "TTD - Trinidad and Tobago Dollar"},
{"symbol" : "TVD", "name" : "TVD - Tuvalu Dollar"},
{"symbol" : "TWD", "name" : "TWD - Taiwan New Dollar"},
{"symbol" : "TZS", "name" : "TZS - Tanzania Shilling"},
{"symbol" : "UAH", "name" : "UAH - Ukraine Hryvna"},
{"symbol" : "UGX", "name" : "UGX - Uganda Shilling"},
{"symbol" : "USD", "name" : "USD - United States Dollar"},
{"symbol" : "UYU", "name" : "UYU - Uruguay Peso"},
{"symbol" : "UZS", "name" : "UZS - Uzbekistan Som"},
{"symbol" : "VEF", "name" : "VEF - Venezuela Bolivar"},
{"symbol" : "VND", "name" : "VND - Viet Nam Dong"},
{"symbol" : "VUV", "name" : "VUV - Vanuatu Vatu"},
{"symbol" : "WST", "name" : "WST - Samoa Tala"},
{"symbol" : "XAF", "name" : "XAF - Communauté Financière Africaine (BEAC) CFA Franc BEAC"},
{"symbol" : "XCD", "name" : "XCD - East Caribbean Dollar"},
{"symbol" : "XDR", "name" : "XDR - International Monetary Fund (IMF) Special Drawing Rights"},
{"symbol" : "XOF", "name" : "XOF - Communauté Financière Africaine (BCEAO) Franc"},
{"symbol" : "XPF", "name" : "XPF - Comptoirs Français du Pacifique (CFP) Franc"},
{"symbol" : "YER", "name" : "YER - Yemen Rial"},
{"symbol" : "ZAR", "name" : "ZAR - South Africa Rand"},
{"symbol" : "ZMW", "name" : "ZMW - Zambia Kwacha"},
{"symbol" : "ZWD", "name" : "ZWD - Zimbabwe Dollar"}
]
